runtime: nodejs18
env: standard
entrypoint: node server.js
handlers:
- url: /.*
  script: auto



# handlers:
# - url: /
#   static_files: dist/event_search/index.html
#   upload: dist/event_search/index.html

# - url: /
#   static_dir: dist/event_search

# # runtime: python27
# # api_version: 1
# # threadsafe: true

# # handlers:
# # - url: /
# #   static_files: dist/event_search/index.html
# #   upload: dist/event_search/index.html

# # - url: /
# #   static_dir: dist/event_search

# # handlers:
# # - url: /.*
# #   static_files: dist/event_search/index.html
# #   upload: dist/event_search/index.html
# # - url: /(.*\.(css|html|js|ico|jpg|png|svg|eot|ttf|woff|woff2))
# #   static_files: dist/event_search/\1
# #   upload: dist/event_search/(.*\.(css|html|js|ico|jpg|png|svg|eot|ttf|woff|woff2))
# handlers:
# - url: /.*
#   script: auto
#   secure: always