runtime: nodejs18
env: standard
# entrypoint: node server.js
service: default
# handlers:
# - url: /(.*\.(css|png|jpg|gif|ico|json|svg))
#   static_files: dist/event_search/\1
#   upload: dist/event_search/(.*\.(css|png|jpg|gif|ico|json|svg))
#   secure: always
#   http_headers:
#     Access-Control-Allow-Origin: "*"
#     Content-Type: ""

# - url: /(.*\.js)
#   static_files: dist/event_search/\1
#   upload: dist/event_search/(.*\.js)
#   secure: always
#   http_headers:
#     Access-Control-Allow-Origin: "*"
#     Content-Type: "application/javascript"

# - url: /.*
#   script: auto
